name: example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  mawa_package:
        path: ../
  flutter_uploader: ^3.0.0-beta.4

  file_picker: ^5.0.1
#  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
#  shared_preferences: ^2.0.15
  flutter_local_notifications: ^9.7.0
#  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "../mawa-flutter-package/lib/assets/images/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "../mawa-flutter-package/lib/assets/images/app_icon.png"
  adaptive_icon_foreground: "../mawa-flutter-package/lib/assets/images/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - packages/mawa_package/assets/images/app_icon.png
    - packages/mawa_package/assets/images/appicon.png

