name: mawa_package
description: A new Flutter project.
version: 0.0.3
homepage:

environment:
  sdk: ">=3.0.0 <=3.13.2"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  rflutter_alert: ^2.0.4
  awesome_dialog: ^3.1.0
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  http: ^0.13.4
  intl: ^0.17.0
  package_info_plus: ^4.0.0
  device_info_plus: ^9.0.0
  email_validator: ^2.0.1
  another_flushbar: ^1.10.29
  permission_handler: ^9.0.2
  fluttertoast: ^8.0.9
#  device_info: ^2.0.2
#  geolocator: ^7.1.1
  stop_watch_timer: ^1.5.0
  dio: ^4.0.6
  path_provider: ^2.0.11
  device_information: ^0.0.4
  geolocator: ^8.0.5
  geocoding: ^2.0.4
  dropdown_search: ^5.0.6
  file_picker: ^5.3.0
  flutter_animate: ^4.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "assets/images/appicon.png"
  android: true
  ios: true
  remove_alpha_ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
#  assets:
#    - assets/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
